--- 
updates: 
  - 
    directory: /ui
    package-ecosystem: npm
    schedule: 
      interval: daily
  - 
    directory: /
    package-ecosystem: npm
    schedule: 
      interval: daily
version: 2
