version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  # node:
  #   container_name: node
  #   build:
  #     context: ./ui
  #   hostname: node
  #   # volumes:
  #   #   - <<: *services-volume
  #   #     source: ./common
  #   #     target: /usr/src/common
  #   networks:
  #     - docker_network
  #   ports:
  #     - 3000:3000
  wss:
    container_name: wss
    build:
      context: ./
    hostname: wss
    networks:
      - docker_network
    ports:
      - 8888:8888
      - 3500:3500
    links:
      - wsspostgres:app_db
    environment:
      FLAVOR: deploy
      DB_USER: table_admin
      DB_NAME: webapp
      DB_PASSWORD: ${USERPWD}
      DB_HOST: app_db
      DB_PORT: 5432
  wsspostgres:
    container_name: wsspostgres
    build:
      context: ./cmd/db
    volumes:
      - <<: *services-volume
        source: ${HOST}/wsspostgres
        target: /var/lib/wsspostgres
    expose:
      - 5432
    hostname: wsspostgres
    networks:
      - docker_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: webapp
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${USERPWD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
