version: "3.5"
x-services-volume: &services-volume
  type: bind

services:
  wsspostgres:
    container_name: wsspostgres
    build:
      context: ./
    volumes:
      - <<: *services-volume
        source: ${HOST}/wsspostgres
        target: /var/lib/wsspostgres
    ports:
      - 5432:5432
    hostname: postgres
    networks:
      - docker_network
    environment:
      #PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: webapp
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: table_admin
      POSTGRES_PASSWORD: ${USERPWD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8

networks:
  docker_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
